spring:
  datasource:
    url: jdbc:mysql://81.68.87.244:3306/multi_chat?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 30002